name: shoe_visual_customizer_mobile
description: Flutter scanner MVP for Shoe Visual Customizer.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0+2
  dio: ^5.7.0
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
